name: Create Certificate SSL
description: Create Certificate SSL in use apache and outhers
inputs:
  apikey-zerossl:
    description: zerossl.com api access key
    required: true
  ssl-csr:
    description: the CSR certificate ( BEGIN CERTIFICATE REQUEST ) in 2048 key size, can be created at https://csrgenerator.com/
    required: true
outputs:
  valid:
    description: getting the certificate hash
runs:
  using: node16 
  main: ./validCSR.js
branding:
  icon: unlock
  color: gray-dark