name: Create Certificate SSL
description: Create Certificate SSL in use apache and outhers
inputs:
  ssl_path:
    description: Path where to save the generated certificates
    required: false
    default: ${{ github.workspace }}
  apikey_zerossl:
    description: zerossl.com api access key
    required: true
  ssl_id:
    description: hash of the certificate for validation 
    required: true
  ssl_csr_priv:
    description: csr private 
    required: true
outputs:
  certificate:
    description: zerossl.com api access key
  ca_bundle:
    description: zerossl.com api access key
runs:
  using: node16
  main: ./downloadCertificate.js
branding:
  icon: unlock
  color: gray-dark