name: Certificate ZeroSSL
on: 
  push:
jobs:
  checkCertificate:
    name: Test Certificate ZeroSSL
    runs-on: ubuntu-latest
    steps:
      - name: DownLoad action
        uses: actions/checkout@v3
        with:
          repository: TiagoSantos01/ZeroSSL
          path: ./.actions/
          ref: main
      - name: Check Certifcate exist
        id: check_certificate
        uses: ./.actions/CheckCertificate
        with:
          apikey-zerossl: '${{ secrets.APIKEY_ZEROSSL }}'
          ssl-certificate-status  : issued
          ssl-dns: '${{ secrets.DNS }}'
      - name: Valid CSR
        if: needs.checkCertificate.check_certificate.id == ''
        id: csr
        uses: ./.actions/ValidCSR
        with:
          apikey-zerossl: '${{ secrets.APIKEY_ZEROSSL }}'
          ssl-csr: '${{ secrets.CSR }}'   
      - name: Create Certicate
        if: needs.checkCertificate.csr.valid == 'true'
        id: create-certificate
        uses: ./.actions/CreateCertificate
        with:
          apikey-zerossl: '${{ secrets.APIKEY_ZEROSSL }}'
          ssl-dns: '${{ secrets.DNS }}'    
          ssl-csr: '${{ secrets.CSR }}'   
          ssl-validaty-days: 30
          ssl-strict-domains: 1







