name: Certificate ZeroSSL
on: 
  push:
jobs:
  checkCertificate:
    name: Test Certificate ZeroSSL
    runs-on: ubuntu-latest
    steps:
      - name: DownLoad action
        uses: actions/checkout@v2
        with:
          repository: TiagoSantos01/ZeroSSL
          path: ./.actions/
          ref: main
      - name: Check Certifcate exist
        id: check-certificate
        uses: ./.actions/src/checkCertificate.js
        with:
          apikey-zerossl: '${{ secrets.APIKEY-ZEROSSL }}'
          ssl-certificate-status  : issued
          ssl-dns: '${{ secrets.DNS }}'







